/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JOptionPane;
import Negocio.Aluno;
import Negocio.Curso;
import java.util.ArrayList;

/**
 *
 * @author ANA
 */
public class TelaModalidade extends javax.swing.JFrame {

    /**
     * Creates new form TelaAluno
     */
    private ArrayList<Aluno> listaAluno = new ArrayList<Aluno>();
    private ArrayList<Curso> listaCurso = new ArrayList<Curso>();
    
    public TelaModalidade(ArrayList<Aluno> listaAluno, ArrayList<Curso> listaCurso) {
        initComponents();
        this.listaAluno = listaAluno;
        this.listaCurso = listaCurso;
        opcaoMatutino.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTurno = new javax.swing.ButtonGroup();
        tituloTela = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelMatricula1 = new javax.swing.JLabel();
        labelCurso = new javax.swing.JLabel();
        textMatricula = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();
        opcaoCurso = new javax.swing.JComboBox<>();
        botaoSalvar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        labelTurno = new javax.swing.JLabel();
        opcaoMatutino = new javax.swing.JRadioButton();
        opcaoVespertino = new javax.swing.JRadioButton();
        opcaoNoturno = new javax.swing.JRadioButton();
        alunoEspecial = new javax.swing.JCheckBox();
        labelEndereco = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textEndereco = new javax.swing.JTextArea();
        labelSenha = new javax.swing.JLabel();
        textSenha1 = new javax.swing.JPasswordField();
        labelSenha1 = new javax.swing.JLabel();
        textSenha2 = new javax.swing.JPasswordField();
        botaoPesquisar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Aluno");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tituloTela.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloTela.setText("Cadastro de Alunos");

        labelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNome.setText("Nome:");

        labelMatricula1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMatricula1.setText("Matrícula:");

        labelCurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCurso.setText("Curso:");

        textMatricula.setBackground(new java.awt.Color(0, 0, 255));

        opcaoCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADM", "Direito", "Medicina", "SI" }));

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");

        labelTurno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTurno.setText("Turno:");

        grupoTurno.add(opcaoMatutino);
        opcaoMatutino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcaoMatutino.setText("Matutino");
        opcaoMatutino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoMatutinoActionPerformed(evt);
            }
        });

        grupoTurno.add(opcaoVespertino);
        opcaoVespertino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcaoVespertino.setText("Vespertino");
        opcaoVespertino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoVespertinoActionPerformed(evt);
            }
        });

        grupoTurno.add(opcaoNoturno);
        opcaoNoturno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcaoNoturno.setText("Noturno");
        opcaoNoturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoNoturnoActionPerformed(evt);
            }
        });

        alunoEspecial.setText("Aluno Especial");

        labelEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEndereco.setText("Endereço:");

        textEndereco.setColumns(20);
        textEndereco.setRows(5);
        jScrollPane1.setViewportView(textEndereco);

        labelSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSenha.setText("Senha:");

        textSenha1.setText("jPasswordField1");

        labelSenha1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSenha1.setText("Confirmação da Senha:");

        textSenha2.setText("jPasswordField1");
        textSenha2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textSenha2FocusLost(evt);
            }
        });

        botaoPesquisar1.setText("Pesquisar");
        botaoPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCurso)
                            .addComponent(labelNome)
                            .addComponent(labelTurno)
                            .addComponent(labelEndereco)
                            .addComponent(labelSenha))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoPesquisar1))
                            .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(botaoSalvar)
                                .addGap(40, 40, 40)
                                .addComponent(botaoExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelSenha1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(opcaoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opcaoMatutino)
                                .addGap(30, 30, 30)
                                .addComponent(opcaoVespertino)
                                .addGap(34, 34, 34)
                                .addComponent(opcaoNoturno))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alunoEspecial)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(tituloTela)))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(labelMatricula1)
                    .addContainerGap(617, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tituloTela)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisar1))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCurso)
                    .addComponent(opcaoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTurno)
                    .addComponent(opcaoMatutino)
                    .addComponent(opcaoVespertino)
                    .addComponent(opcaoNoturno))
                .addGap(18, 18, 18)
                .addComponent(alunoEspecial)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEndereco)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSenha)
                            .addComponent(textSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSenha1)
                            .addComponent(textSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(78, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoSalvar)
                            .addComponent(botaoExcluir))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(labelMatricula1)
                    .addContainerGap(349, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // TODO add your handling code here:
        if (camposValidos()){
        Aluno a1;
        int mat = Integer.parseInt(textMatricula.getText());
        int turno;
        if (opcaoMatutino.isSelected())
            turno = 1;
        else if (opcaoVespertino.isSelected())
            turno = 2;
        else
            turno=3;
        a1 = new Aluno(textNome.getText(),mat,opcaoCurso.getSelectedItem().toString(),turno );
        listaAluno.add(a1);
        JOptionPane.showMessageDialog(null, "Aluno incluído com sucesso!");
        limpar();
        }
        
    }//GEN-LAST:event_botaoSalvarActionPerformed
    public boolean camposValidos(){
        if (textMatricula.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe a matricula");
            return false;
        }
        else if (textNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe o nome do aluno");
            return false;
        }
        else if (opcaoCurso.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(null, "Informe o curso");
            return false;
        }
        else
            return true;
            
            
            
    }
    private void botaoPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisar1ActionPerformed
        // TODO add your handling code here:
        int mat = Integer.parseInt(textMatricula.getText());
        for (Aluno alu: listaAluno){
            if (alu.getMatricula()==mat){
                textNome.setText(alu.getNome());
                if (alu.getTurno()==1)
                    opcaoMatutino.setSelected(true);
                else if (alu.getTurno()==2)
                    opcaoVespertino.setSelected(true);
                else
                    opcaoNoturno.setSelected(true);
                if (alu.getCurso().equals("ADM"))
                    opcaoCurso.setSelectedIndex(0);
                else if (alu.getCurso().equals("Direito"))
                    opcaoCurso.setSelectedIndex(1);
                else if (alu.getCurso().equals("Medicina"))
                    opcaoCurso.setSelectedIndex(2);
                else
                    opcaoCurso.setSelectedIndex(3);
            }
        }
    }//GEN-LAST:event_botaoPesquisar1ActionPerformed

    private void opcaoMatutinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoMatutinoActionPerformed
        // TODO add your handling code here:
        alunoEspecial.setVisible(false);
    }//GEN-LAST:event_opcaoMatutinoActionPerformed

    private void opcaoVespertinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoVespertinoActionPerformed
        // TODO add your handling code here:
        alunoEspecial.setVisible(false);
    }//GEN-LAST:event_opcaoVespertinoActionPerformed

    private void opcaoNoturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoNoturnoActionPerformed
        // TODO add your handling code here:
        alunoEspecial.setVisible(true);
    }//GEN-LAST:event_opcaoNoturnoActionPerformed

    private void textSenha2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSenha2FocusLost
        // TODO add your handling code here:
        if (!textSenha1.getText().equals(textSenha2.getText()))
            JOptionPane.showMessageDialog(null, "sua senha não confere.");
    }//GEN-LAST:event_textSenha2FocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        opcaoCurso.removeAllItems();
        for (Curso c:listaCurso){
            opcaoCurso.addItem(c.getNomeCurso());
        }        
    }//GEN-LAST:event_formWindowOpened

    public void limpar(){
        textMatricula.setText("");
        textNome.setText("");
        opcaoCurso.setSelectedIndex(0);
        opcaoMatutino.setSelected(true);
        
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alunoEspecial;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoPesquisar1;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.ButtonGroup grupoTurno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCurso;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelMatricula1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSenha1;
    private javax.swing.JLabel labelTurno;
    private javax.swing.JComboBox<String> opcaoCurso;
    private javax.swing.JRadioButton opcaoMatutino;
    private javax.swing.JRadioButton opcaoNoturno;
    private javax.swing.JRadioButton opcaoVespertino;
    private javax.swing.JTextArea textEndereco;
    private javax.swing.JTextField textMatricula;
    private javax.swing.JTextField textNome;
    private javax.swing.JPasswordField textSenha1;
    private javax.swing.JPasswordField textSenha2;
    private javax.swing.JLabel tituloTela;
    // End of variables declaration//GEN-END:variables
}
