/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Tela;

import java.util.ArrayList;
import Negocio.Aluno;
import Negocio.Matricula;
import Negocio.Modalidade;
import Negocio.ModalidadeDiaria;
import Negocio.ModalidadeLivre;
/**
 *
 * @author luiz
 */
public class Principal extends javax.swing.JFrame {
    private ArrayList<Aluno> listaAluno = new ArrayList<>();
    private ArrayList<Modalidade> listaModalidade = new ArrayList<>();
    private ArrayList<Matricula> listaMatricula = new ArrayList<>();
    private ArrayList<ModalidadeDiaria> listaModalidadeDiaria = new ArrayList<>();
    private ArrayList<ModalidadeLivre> listaModalidadeLivre = new ArrayList<>();
   
    private ArrayList<Matricula> listaDevedores = new ArrayList<>();

    
    /**
     * Creates new form principal
     */
    public Principal() {
        initComponents();
    }

    
    public Principal(ArrayList<Aluno> listaAluno,ArrayList<Modalidade> listaModalidade, ArrayList<Matricula> listaMatricula,ArrayList<ModalidadeLivre> listaModalidadeLivre,ArrayList<ModalidadeDiaria> listaModalidadeDiaria) {
        initComponents();
        this.listaAluno = listaAluno;
        this.listaModalidade = listaModalidade;
        this.listaMatricula = listaMatricula;
        this.listaModalidadeDiaria= listaModalidadeDiaria;
        this.listaModalidadeLivre= listaModalidadeLivre;
        this.listaDevedores =listaDevedores;


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroPrincipal = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        Aluno = new javax.swing.JMenu();
        cadAluno = new javax.swing.JMenuItem();
        cadAlunoMenor = new javax.swing.JMenuItem();
        cadMatricula = new javax.swing.JMenuItem();
        login = new javax.swing.JMenu();
        cadLogin = new javax.swing.JMenuItem();
        pagar = new javax.swing.JMenu();
        pagarModalidade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Alunos matriculados em 2 modalidades", "5% desconto"},
                {"Alunos matriculados em 3 ou mais modalidades", "20% desconto"},
                {"Estudantes", "10% desconto"},
                {"Parentes(caso tenham pessoas da mesma família)", "10% desconto"},
                {null, null}
            },
            new String [] {
                "Descrição do desconto", "Percentual do desconto"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        cadastroPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 710, 130);

        Aluno.setMnemonic('f');
        Aluno.setText("Cadastro");
        Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlunoActionPerformed(evt);
            }
        });

        cadAluno.setMnemonic('o');
        cadAluno.setText("Aluno");
        cadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAlunoActionPerformed(evt);
            }
        });
        Aluno.add(cadAluno);

        cadAlunoMenor.setMnemonic('s');
        cadAlunoMenor.setText("Alunor menor");
        cadAlunoMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAlunoMenorActionPerformed(evt);
            }
        });
        Aluno.add(cadAlunoMenor);

        cadMatricula.setMnemonic('a');
        cadMatricula.setText("Matricula");
        cadMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMatriculaActionPerformed(evt);
            }
        });
        Aluno.add(cadMatricula);

        menuBar.add(Aluno);

        login.setMnemonic('e');
        login.setText("Acesso");

        cadLogin.setMnemonic('t');
        cadLogin.setText("Login");
        cadLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadLoginActionPerformed(evt);
            }
        });
        login.add(cadLogin);

        menuBar.add(login);

        pagar.setMnemonic('h');
        pagar.setText("Pagamento");
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarActionPerformed(evt);
            }
        });

        pagarModalidade.setMnemonic('c');
        pagarModalidade.setText("Pagar");
        pagarModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarModalidadeActionPerformed(evt);
            }
        });
        pagar.add(pagarModalidade);

        menuBar.add(pagar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cadastroPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastroPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAlunoActionPerformed
        // TODO add your handling code here:
        TelaAluno telaAluno = new TelaAluno(listaAluno);
        telaAluno.setVisible(true);
    }//GEN-LAST:event_cadAlunoActionPerformed

    private void cadAlunoMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAlunoMenorActionPerformed
        // TODO add your handling code here:
        TelaAlunoMenor telaAlunoMenor = new TelaAlunoMenor(listaAluno);
        telaAlunoMenor.setVisible(true);
    }//GEN-LAST:event_cadAlunoMenorActionPerformed

    private void cadMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMatriculaActionPerformed
        // TODO add your handling code here:
        TelaMatricula telaMatricula = new TelaMatricula(listaAluno,listaModalidade,listaMatricula,listaModalidadeLivre,listaModalidadeDiaria);
        telaMatricula.setVisible(true);
    }//GEN-LAST:event_cadMatriculaActionPerformed

    private void cadLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadLoginActionPerformed
        // TODO add your handling code here:
        TelaLogin telaLogin = new TelaLogin(listaMatricula,listaAluno);
        telaLogin.setVisible(true);
    }//GEN-LAST:event_cadLoginActionPerformed

    private void pagarModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarModalidadeActionPerformed
        // TODO add your handling code here:
        TelaPagar telaPagar = new TelaPagar(listaMatricula,listaAluno);
        telaPagar.setVisible(true);
    }//GEN-LAST:event_pagarModalidadeActionPerformed

    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pagarActionPerformed

    private void AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Aluno;
    private javax.swing.JMenuItem cadAluno;
    private javax.swing.JMenuItem cadAlunoMenor;
    private javax.swing.JMenuItem cadLogin;
    private javax.swing.JMenuItem cadMatricula;
    private javax.swing.JDesktopPane cadastroPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu login;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu pagar;
    private javax.swing.JMenuItem pagarModalidade;
    // End of variables declaration//GEN-END:variables

}
