/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import Negocio.Aluno;
import Negocio.Matricula;
import Negocio.Modalidade;
import Negocio.ModalidadeLivre;
import Negocio.ModalidadeDiaria;
import Negocio.Pagamento;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author luiz
 */
public class TelaMatricula extends javax.swing.JFrame {

    /*criei para não ter problemas ao trabalhar com objetos em métodos diferentes*/
    private String nome = " ";
    private String turma = " ";
    private String dia = " ";
    private float preco = 0;
    private int contModalidades = 0;
    private Aluno aluno;
    private Pagamento pagamento;
    
    private ArrayList<Aluno> listaAluno = new ArrayList<>();
    private ArrayList<Modalidade> listaModalidade = new ArrayList<>();
    private ArrayList<ModalidadeDiaria> listaModalidadeDiaria = new ArrayList<>();
    private ArrayList<ModalidadeLivre> listaModalidadeLivre = new ArrayList<>();
                       
    private ArrayList<Matricula> listaMatricula = new ArrayList<>();

    public TelaMatricula() {
        initComponents();
    }

    public TelaMatricula(ArrayList<Aluno> lista, ArrayList<Modalidade> modalidade, ArrayList<Matricula> matricula,ArrayList<ModalidadeLivre> modalidadeLivre,ArrayList<ModalidadeDiaria> modalidadeDiaria) {
        initComponents();
        this.listaAluno = lista;
        this.listaModalidade = modalidade;
        this.listaModalidadeDiaria = modalidadeDiaria;
        this.listaModalidadeLivre = modalidadeLivre;
        this.listaMatricula = matricula;
        preencheListaMatricula();
    }

    
    public String matriculado(String nome){
        String matriculado = "";
        for(int j=0;j<listaMatricula.size();j++){
            if(listaMatricula.get(j).getAluno().equals(nome)){
                matriculado = listaMatricula.get(j).getAluno(); 
            }
        }
        
        return matriculado;
    }
    
    public void preencheListaMatricula() {
        for (int i = 0; i < listaAluno.size(); i++) {
            String aluno = listaAluno.get(i).getNome();
            if(!(matriculado(aluno).equals(aluno)))
            campoAluno.addItem(aluno);
        }
    }
    
    
    /*criei para não ter problemas ao trabalhar com objetos em métodos diferentes*/
    public void capTuraNome(String nome) {
        this.nome += nome + ", ";
    }

    public String getCapturaNome() {
        return nome;
    }

    public void capturaPreco(float preco) {
        this.preco += preco;
    }

    public float getCapturaPreco() {
        return preco;
    }

    public void capturaTurma(String turma) {
        this.turma += turma + ", ";
    }

    public String getCapturaTurma() {
        return turma;
    }

    public void capturaDia(String dia) {
        this.dia += dia + ", ";
    }

    public String getCapturaDia() {
        return dia;
    }

    public boolean capturaParente() {
        boolean parente = false;
        for (int i = 0; i < listaAluno.size(); i++) {
            if (campoAluno.getModel().getSelectedItem().toString().equals(listaAluno.get(i).getNome())) {
                parente = listaAluno.get(i).isEstudante();
            }
        }
        return parente;
    }

    public boolean capturaEstudante() {
        boolean estudante = false;
        for (int i = 0; i < listaAluno.size(); i++) {
            if (campoAluno.getModel().getSelectedItem().toString().equals(listaAluno.get(i).getNome())) {
                estudante = listaAluno.get(i).isEstudante();
            }
        }
        return estudante;
    }

    public Pagamento getPagamento() {
        return pagamento;
    }

    public void gravarPagamento(Pagamento pagamento) {
        this.pagamento = pagamento;
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        campoLogin = new javax.swing.JTextField();
        campoAluno = new javax.swing.JComboBox<>();
        campoSenha = new javax.swing.JPasswordField();
        labelNome8 = new javax.swing.JLabel();
        tituloTela1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabela1 = new javax.swing.JTable();
        musculacao = new javax.swing.JCheckBox();
        pilates = new javax.swing.JCheckBox();
        tituloTela3 = new javax.swing.JLabel();
        labelNome9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        turma2_ginastica = new javax.swing.JCheckBox();
        turma1_ginastica = new javax.swing.JCheckBox();
        natacao = new javax.swing.JCheckBox();
        ginastica = new javax.swing.JCheckBox();
        turma2_natacao = new javax.swing.JCheckBox();
        turma1_natacao = new javax.swing.JCheckBox();
        inserir = new javax.swing.JButton();
        campoDataPagamento = new javax.swing.JFormattedTextField();
        labelEndereco1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("telaMatricula"); // NOI18N

        campoLogin.setName("campoLogin"); // NOI18N
        campoLogin.setOpaque(true);

        campoSenha.setText("jPasswordField1");
        campoSenha.setName("campoSenha"); // NOI18N

        labelNome8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNome8.setText("Senha");
        labelNome8.setName("senha"); // NOI18N

        tituloTela1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloTela1.setText("Matrícula");

        Tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pilates", "R$ 200,00"},
                {"Musculação", "R$ 250,00"}
            },
            new String [] {
                "Nome", "Preço"
            }
        ));
        Tabela1.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(Tabela1);

        musculacao.setText("Musculação");
        musculacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musculacaoActionPerformed(evt);
            }
        });

        pilates.setText("Pilates");
        pilates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilatesActionPerformed(evt);
            }
        });

        tituloTela3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloTela3.setText("Credenciais de acesso");

        labelNome9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNome9.setText("Login");
        labelNome9.setName("senha"); // NOI18N

        jLabel1.setText("Modalidade livre");

        jLabel2.setText("Modalidade Diária");

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Natação", "R$ 200,00", "Seg e ter 9:00 - 11:00", "Seg e Ter 14:00 - 15:00"},
                {"Gisnática", "R$ 250,00", "Quar e quin 9:00 - 11:00", "Quar e Quin 14:00 - 15:00"}
            },
            new String [] {
                "Nome", "Preço", "Turma 1", "Turma 2"
            }
        ));
        Tabela.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(Tabela);
        Tabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        turma2_ginastica.setText("Turma 2");
        turma2_ginastica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turma2_ginasticaActionPerformed(evt);
            }
        });

        turma1_ginastica.setText("Turma 1");
        turma1_ginastica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turma1_ginasticaActionPerformed(evt);
            }
        });

        natacao.setText("Natação");
        natacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                natacaoActionPerformed(evt);
            }
        });

        ginastica.setText("Ginástica");
        ginastica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ginasticaActionPerformed(evt);
            }
        });

        turma2_natacao.setText("Turma 2");
        turma2_natacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turma2_natacaoActionPerformed(evt);
            }
        });

        turma1_natacao.setText("Turma 1");
        turma1_natacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turma1_natacaoActionPerformed(evt);
            }
        });

        inserir.setText("Salvar");
        inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirActionPerformed(evt);
            }
        });

        try {
            campoDataPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoDataPagamento.setToolTipText("");
        campoDataPagamento.setName("campoData"); // NOI18N

        labelEndereco1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEndereco1.setText("Data de pagamento");
        labelEndereco1.setName("dataIngresso"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(tituloTela3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(inserir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addGap(335, 335, 335)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(tituloTela1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(labelNome9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNome8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pilates)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(musculacao))
                                    .addComponent(labelEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(campoDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(natacao)
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(turma2_natacao)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(turma1_natacao)
                                        .addGap(31, 31, 31)
                                        .addComponent(ginastica))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(campoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(turma2_ginastica)
                            .addComponent(turma1_ginastica))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(tituloTela1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pilates)
                            .addComponent(musculacao)
                            .addComponent(natacao)
                            .addComponent(ginastica)
                            .addComponent(turma1_natacao)
                            .addComponent(turma1_ginastica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(turma2_natacao)
                            .addComponent(turma2_ginastica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(labelEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(tituloTela3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNome9)
                            .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNome8)
                            .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(inserir)
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musculacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musculacaoActionPerformed
        // TODO add your handling code here:
        capTuraNome(musculacao.getText());
        capturaPreco(250);
        this.contModalidades++;
    }//GEN-LAST:event_musculacaoActionPerformed

    private void pilatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilatesActionPerformed
        // TODO add your handling code here:
        capTuraNome(pilates.getText());
        capturaPreco(200);
        this.contModalidades++;
    }//GEN-LAST:event_pilatesActionPerformed

    /*limpar tela*/
    public void limparModalidadeLivre() {
        musculacao.setSelected(false);
        pilates.setSelected(false);
        campoDataPagamento.setText("");
        this.nome = " ";/*resta a captura de nomes*/
        this.preco = 0;
    }
    
    public void limpar() {
        campoLogin.setText("");
        campoSenha.setText("");
        int index = campoAluno.getSelectedIndex();
        campoAluno.removeItemAt(index);
    }

    public void limparModalidadeDiaria() {
        ginastica.setSelected(false);
        natacao.setSelected(false);
        turma1_natacao.setSelected(false);
        turma2_natacao.setSelected(false);
        turma1_ginastica.setSelected(false);
        turma2_ginastica.setSelected(false);
        campoDataPagamento.setText("");

        this.nome = " ";/*resta a captura de nomes*/
        this.preco = 0;
        this.turma = " ";
        this.dia = " ";
    }

    private void natacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_natacaoActionPerformed
        // TODO add your handling code here:
        capTuraNome(natacao.getText());
        capturaPreco(200);
        this.contModalidades++;
    }//GEN-LAST:event_natacaoActionPerformed

    private void ginasticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ginasticaActionPerformed
        capTuraNome(ginastica.getText());
        capturaPreco(250);
        this.contModalidades++;
    }//GEN-LAST:event_ginasticaActionPerformed
    
    /*Botão para inserir modalidade*/
    private void inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirActionPerformed
       
        String aluno = campoAluno.getModel().getSelectedItem().toString();
               
        ModalidadeDiaria diaria = new ModalidadeDiaria(getCapturaTurma(), getCapturaDia(), getCapturaNome(), getCapturaPreco(),aluno);
        ModalidadeLivre livre = new ModalidadeLivre(getCapturaNome(),getCapturaPreco(),aluno);
        listaModalidadeDiaria.add(diaria);
        listaModalidadeLivre.add(livre);
        /*revisar desconto*/
        Pagamento pagamento = new Pagamento(getCapturaPreco());
        pagamento.calcularDesconto(getCapturaPreco(),capturaEstudante(),capturaParente(),contModalidades);
        Matricula matricula = new Matricula(campoLogin.getText(), campoSenha.getText(),aluno,diaria,pagamento);
        matricula.setMatriculado(true);
        listaMatricula.add(matricula);
       
        JOptionPane.showMessageDialog(null, "Incluido com sucesso!");
        
        limpar();
        limparModalidadeDiaria();
        limparModalidadeLivre();
        
    }//GEN-LAST:event_inserirActionPerformed

    private void turma1_natacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turma1_natacaoActionPerformed
        // TODO add your handling code here:
        capturaTurma("Natação : turma 1");
        capturaDia("Natação: Seg e ter - turma 1");
    }//GEN-LAST:event_turma1_natacaoActionPerformed

    private void turma2_natacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turma2_natacaoActionPerformed
        // TODO add your handling code here:
        capturaTurma("Natação : turma 2");
        capturaDia("Natação: Seg e ter - turma 2");
    }//GEN-LAST:event_turma2_natacaoActionPerformed

    private void turma1_ginasticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turma1_ginasticaActionPerformed
        // TODO add your handling code here:
        capturaTurma("Ginástica : turma 1");
        capturaDia("Ginástica: Quar e quin - turma 1");
    }//GEN-LAST:event_turma1_ginasticaActionPerformed

    private void turma2_ginasticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turma2_ginasticaActionPerformed
        // TODO add your handling code here:
        capturaTurma("Ginástica : turma 2");
        capturaDia("Ginástica: Quar e quin - turma 2");
    }//GEN-LAST:event_turma2_ginasticaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JTable Tabela1;
    private javax.swing.JComboBox<String> campoAluno;
    private javax.swing.JFormattedTextField campoDataPagamento;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JCheckBox ginastica;
    private javax.swing.JButton inserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelEndereco1;
    private javax.swing.JLabel labelNome8;
    private javax.swing.JLabel labelNome9;
    private javax.swing.JCheckBox musculacao;
    private javax.swing.JCheckBox natacao;
    private javax.swing.JCheckBox pilates;
    private javax.swing.JLabel tituloTela1;
    private javax.swing.JLabel tituloTela3;
    private javax.swing.JCheckBox turma1_ginastica;
    private javax.swing.JCheckBox turma1_natacao;
    private javax.swing.JCheckBox turma2_ginastica;
    private javax.swing.JCheckBox turma2_natacao;
    // End of variables declaration//GEN-END:variables
}
