/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import Negocio.Aluno;
import Negocio.Matricula;
import Negocio.Modalidade;
import Negocio.ModalidadeLivre;
import Negocio.ModalidadeDiaria;
import Negocio.Pagamento;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author luiz
 */
public class TelaPagar extends javax.swing.JFrame {

    /*criei para não ter problemas ao trabalhar com objetos em métodos diferentes*/
 
    
    private ArrayList<Aluno> listaAluno = new ArrayList<>();
    private ArrayList<Modalidade> listaModalidade = new ArrayList<>();
    private ArrayList<ModalidadeDiaria> listaModalidadeDiaria = new ArrayList<>();
    private ArrayList<ModalidadeLivre> listaModalidadeLivre = new ArrayList<>();
    private ArrayList<Matricula> listaMatricula = new ArrayList<>();


    public TelaPagar() {
        initComponents();
    }

    public TelaPagar(ArrayList<Matricula> matricula,ArrayList<Aluno> aluno) {
        initComponents();
        this.listaMatricula = matricula;
        this.listaAluno = aluno;
        
        listarNomes();
    }

    public void listarNomes(){
        for(int i=0;i<listaMatricula.size();i++){
            boolean pago = listaMatricula.get(i).getPagamento().isPago();
            if(!pago){
                campoAluno.addItem(listaMatricula.get(i).getAluno());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        campoAluno = new javax.swing.JComboBox<>();
        tituloTela1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabela1 = new javax.swing.JTable();
        buscarPagador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        pagar = new javax.swing.JButton();
        campoPreco = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoPagamentoTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloTela1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloTela1.setText("Pagar");

        Tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pilates", "R$ 200,00"},
                {"Musculação", "R$ 250,00"}
            },
            new String [] {
                "Nome", "Preço"
            }
        ));
        Tabela1.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(Tabela1);

        buscarPagador.setText("Buscar pagador");
        buscarPagador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPagadorActionPerformed(evt);
            }
        });

        jLabel1.setText("Modalidade livre");

        jLabel2.setText("Modalidade Diária");

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Natação", "R$ 200,00", "Seg e ter 9:00 - 11:00", "Seg e Ter 14:00 - 15:00"},
                {"Gisnática", "R$ 250,00", "Quar e quin 9:00 - 11:00", "Quar e Quin 14:00 - 15:00"}
            },
            new String [] {
                "Nome", "Preço", "Turma 1", "Turma 2"
            }
        ));
        Tabela.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(Tabela);
        Tabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        pagar.setText("Pagar");
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarActionPerformed(evt);
            }
        });

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome");

        jLabel4.setText("Preço");

        jLabel5.setText("Pagamento total");

        campoPagamentoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPagamentoTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(campoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addGap(335, 335, 335)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(tituloTela1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(campoPagamentoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(pagar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel5)
                        .addGap(159, 159, 159)
                        .addComponent(buscarPagador)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(tituloTela1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(buscarPagador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPagamentoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(pagar)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Botão para inserir modalidade*/
    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        String aluno = campoAluno.getModel().getSelectedItem().toString();
        for(int i=0;i<listaMatricula.size();i++){
           if(aluno.equals(listaMatricula.get(i).getAluno())){
               /*sai da lista de devedores*/
               listaMatricula.get(i).getPagamento().setPago(true);
               limpar();
              
               JOptionPane.showMessageDialog(null,"Pago!");
           }
       }     
    }//GEN-LAST:event_pagarActionPerformed

    private void buscarPagadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPagadorActionPerformed
        String aluno = campoAluno.getModel().getSelectedItem().toString();
        for(int i=0;i<listaMatricula.size();i++){
            if(listaMatricula.get(i).getAluno().equals(aluno)&&listaMatricula.get(i).getPagamento().getValorPagamento()!=0){  
                campoNome.setText(listaMatricula.get(i).getModalidade().getNome());
                campoPreco.setText(String.valueOf(listaMatricula.get(i).getModalidade().getPreco()));
                campoPagamentoTotal.setText(String.valueOf(listaMatricula.get(i).getPagamento().getValorPagamento()));
           }
        }
    }//GEN-LAST:event_buscarPagadorActionPerformed

    public void limpar(){
        campoNome.setText("");
        campoPreco.setText("");
        campoPagamentoTotal.setText("");
        
    }
    
    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoPagamentoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPagamentoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPagamentoTotalActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JTable Tabela1;
    private javax.swing.JButton buscarPagador;
    private javax.swing.JComboBox<String> campoAluno;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPagamentoTotal;
    private javax.swing.JTextField campoPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton pagar;
    private javax.swing.JLabel tituloTela1;
    // End of variables declaration//GEN-END:variables
}
