/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Ana
 */
public class CadAluno extends javax.swing.JFrame {

    /**
     * Creates new form CadAluno
     */
    public CadAluno() {
        initComponents();
    }
   public void calcularMensalidade(){
       float mens=0;
       if (opNao.isSelected()){
       if (opIngles.isSelected())
           mens +=100;
       if (opEspanhol.isSelected())
           mens+=100;
       if (opAlemao.isSelected())
           mens+=100;
       }
       tMensalidade.setText(String.valueOf(mens));
   }
   
   public void mudaVisibilidade(boolean val){
        lDesconto.setVisible(val);
        tDesconto.setVisible(val);
        lValor.setVisible(val);
        tValor.setVisible(val);
   }
   
   public void calcularValorFinal(){
       float mens,desc;
       mens = Float.parseFloat(tMensalidade.getText());
       desc = Float.parseFloat(tDesconto.getText());
       tValor.setText(String.valueOf(mens-desc));
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTurno = new javax.swing.ButtonGroup();
        Bolsa = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        tMatricula = new javax.swing.JTextField();
        tCurso = new javax.swing.JComboBox<>();
        opMat = new javax.swing.JRadioButton();
        opVesp = new javax.swing.JRadioButton();
        opNot = new javax.swing.JRadioButton();
        opIngles = new javax.swing.JCheckBox();
        opEspanhol = new javax.swing.JCheckBox();
        opAlemao = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tEndereco = new javax.swing.JTextArea();
        btIncluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tMensalidade = new javax.swing.JTextField();
        lDesconto = new javax.swing.JLabel();
        tDesconto = new javax.swing.JTextField();
        lValor = new javax.swing.JLabel();
        tValor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        opSim = new javax.swing.JRadioButton();
        opNao = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Alunos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Matricula:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Curso:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Turno:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Idiomas:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Endereço:");

        tCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adm", "Direito", "Medicina", "SI" }));

        grupoTurno.add(opMat);
        opMat.setText("Matutino");

        grupoTurno.add(opVesp);
        opVesp.setText("Vespertino");

        grupoTurno.add(opNot);
        opNot.setText("Noturno");

        opIngles.setText("Ingles");
        opIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opInglesActionPerformed(evt);
            }
        });

        opEspanhol.setText("Espanhol");
        opEspanhol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEspanholActionPerformed(evt);
            }
        });

        opAlemao.setText("Alemão");
        opAlemao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opAlemaoActionPerformed(evt);
            }
        });

        tEndereco.setColumns(20);
        tEndereco.setRows(5);
        jScrollPane1.setViewportView(tEndereco);

        btIncluir.setText("Incluir");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Mensalidade:");

        lDesconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lDesconto.setText("Desconto:");

        tDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tDescontoFocusLost(evt);
            }
        });

        lValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lValor.setText("Valor final:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Bolsa?");

        Bolsa.add(opSim);
        opSim.setText("Sim");
        opSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSimActionPerformed(evt);
            }
        });

        Bolsa.add(opNao);
        opNao.setSelected(true);
        opNao.setText("Não");
        opNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btIncluir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lDesconto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tMensalidade, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(tDesconto)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(lValor)
                            .addComponent(jLabel11))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opMat)
                                .addGap(18, 18, 18)
                                .addComponent(opVesp)
                                .addGap(18, 18, 18)
                                .addComponent(opNot))
                            .addComponent(tNome)
                            .addComponent(tMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tValor)
                                .addGap(145, 145, 145))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opIngles)
                                    .addComponent(opSim))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opNao)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(opEspanhol)
                                        .addGap(18, 18, 18)
                                        .addComponent(opAlemao)))))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(opMat)
                        .addComponent(opVesp)
                        .addComponent(opNot)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(opIngles)
                    .addComponent(opEspanhol)
                    .addComponent(opAlemao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(opSim)
                    .addComponent(opNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDesconto)
                    .addComponent(tDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lValor)
                    .addComponent(tValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btIncluir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opInglesActionPerformed
        // TODO add your handling code here:
        calcularMensalidade();
        
    }//GEN-LAST:event_opInglesActionPerformed

    private void opEspanholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEspanholActionPerformed
        // TODO add your handling code here:
        calcularMensalidade();
    }//GEN-LAST:event_opEspanholActionPerformed

    private void opAlemaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opAlemaoActionPerformed
        // TODO add your handling code here:
        calcularMensalidade();
    }//GEN-LAST:event_opAlemaoActionPerformed

    private void opSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSimActionPerformed
        // TODO add your handling code here:
        mudaVisibilidade(false);
        calcularMensalidade();
    }//GEN-LAST:event_opSimActionPerformed

    private void opNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opNaoActionPerformed
        // TODO add your handling code here:
        mudaVisibilidade(true);
        calcularMensalidade();
    }//GEN-LAST:event_opNaoActionPerformed

    private void tDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tDescontoFocusLost
        // TODO add your handling code here:
        calcularValorFinal();
    }//GEN-LAST:event_tDescontoFocusLost

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Bolsa;
    private javax.swing.JButton btIncluir;
    private javax.swing.ButtonGroup grupoTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lDesconto;
    private javax.swing.JLabel lValor;
    private javax.swing.JCheckBox opAlemao;
    private javax.swing.JCheckBox opEspanhol;
    private javax.swing.JCheckBox opIngles;
    private javax.swing.JRadioButton opMat;
    private javax.swing.JRadioButton opNao;
    private javax.swing.JRadioButton opNot;
    private javax.swing.JRadioButton opSim;
    private javax.swing.JRadioButton opVesp;
    private javax.swing.JComboBox<String> tCurso;
    private javax.swing.JTextField tDesconto;
    private javax.swing.JTextArea tEndereco;
    private javax.swing.JTextField tMatricula;
    private javax.swing.JTextField tMensalidade;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tValor;
    // End of variables declaration//GEN-END:variables
}
